services:
  - type: web
    name: elegant-furniture-store
    runtime: node
    plan: starter
    buildCommand: |
      echo "Starting build process..."
      npm run install-all
      echo "Dependencies installed, building application..."
      npm run build
      echo "Build completed, checking build directory..."
      ls -la build/ || echo "Build directory not found"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true 