services:
  - type: web
    name: elegant-furniture-store
    runtime: static
    buildCommand: npm ci && npm run build && ls -la dist/
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 